name: Deploy Backend to Azure (Publish profile, ships node_modules)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: traveltrackbackend
  NODE_VERSION: "20"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Install production dependencies
        working-directory: server
        run: npm ci --omit=dev

      # Zip EVERYTHING in server/, INCLUDING node_modules
      - name: Create zip with node_modules
        run: |
          cd server
          zip -r ../api.zip . -x ".git/*"
          cd ..
        shell: bash

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api.zip
